import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Subtitute Teacher',
    company: 'Njelele High School',
    logo: '/images/careers/riab.png',
    location: 'Gokwe Centre',
    location_type: 'Onsite',
    type: 'Relief',
    start_date: '2013-05',
    end_date: '2013-09',
    industry: 'ota',
    link: '#',
  },
  {
    position: 'Junior Tutor',
    company: 'Jacoh Academic College',
    logo: '/images/careers/flexcode.png',
    location: 'Kuwadzana, Harare',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2016-01',
    end_date: '2016-11',
    industry: 'education',
    link: '#',
  },
  {
    position: 'Senior Tutor',
    company: 'Early Bird',
    logo: '/images/careers/sirka.png',
    location: 'Malbereign, Harare',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2016-12',
    end_date: '2018-12',
    industry: 'education',
    link: '#',
  },
  // {
  //   position: 'Co-Founder & CTO',
  //   company: 'FlexCode',
  //   logo: '/images/careers/flexcode.png',
  //   location: 'Jakarta, ID',
  //   location_type: 'Remote',
  //   type: 'Fulltime',
  //   start_date: '2021-01',
  //   end_date: null,
  //   industry: 'wellness',
  //   link: 'https://flexcode.co.id',
  // },
  {
    position: 'Administrator',
    company: 'Prochoice Pvt Ltd',
    logo: '/images/careers/paper-id.png',
    location: 'Southerton, Harare',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2020-02',
    end_date: '2021-12',
    industry: 'administration',
    link: '#',
  },
  {
    position: 'Freelance Tutor',
    company: 'Sandton',
    logo: '/images/careers/kpn.png',
    location: 'Sandton, Harare',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2021-09',
    end_date: null,
    industry: 'education',
    link: '#',
  },
  // {
  //   position: 'Full Stack Developer',
  //   company: 'Rencong Network',
  //   logo: '/images/careers/rencong.png',
  //   location: 'Aceh, ID',
  //   location_type: 'Onsite',
  //   type: 'Freelance',
  //   start_date: '2014-12',
  //   end_date: '2019-09',
  //   industry: 'software house',
  //   link: 'https://www.linkedin.com/company/rencongnetwork',
  // },
  // {
  //   position: 'Web Developer',
  //   company: 'PT. Kuala Nanggroe',
  //   logo: null,
  //   location: 'Aceh, ID',
  //   location_type: 'Onsite',
  //   type: 'Part-time',
  //   start_date: '2016-12',
  //   end_date: '2017-08',
  //   industry: 'travel',
  //   link: 'https://travelkuala.com',
  // },
  // {
  //   position: 'Web Developer',
  //   company: 'MA Ruhul Islam',
  //   logo: '/images/careers/riab.png',
  //   location: 'Aceh, ID',
  //   location_type: 'Onsite',
  //   type: 'Part-time',
  //   start_date: '2015-01',
  //   end_date: '2016-01',
  //   industry: 'school',
  //   link: 'https://ruhulislam.com',
  // },
];
